services:
  new-project-mailbot:
    restart: always
    image: new-project-mailbot
    container_name: new-project-mailbot
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Europe/Warsaw
    env_file:
      - .env
    volumes:
      - ./app:/code/app
